export const LOG_IN="LOG_IN"
export const REGISTER="REGISTER"
export const GET_CURRENT="GET_CURRENT"
export const LOG_OUT="LOG_OUT"
export const FAIL="FAIL"
export const UPDATE = 'UPDATE'
export const COMMENT = 'COMMENT'
export const GETALL="GETALL"
export const UPDIMG='UPDIMG'